language: smalltalk
sudo: false

notifications:
    email:
        on_success: never
        on_failure: never

os:
- linux

smalltalk:
  - Pharo64-9.0
  - Pharo64-8.0

matrix:
  fast_finish: true
  allow_failures:
    - smalltalk: Pharo64-9.0
    
